

#集群名称
cluster.name: elasticsearch-2.4-local
#节点名称
node.name: zhengxgs-7.238-local

#是否可以选举为主节点，默认为true
#node.master: false

#是否作为数据节点，默认为true
#node.data: false

network.host: 0.0.0.0

#索引缓存引用类型，soft，当内存不足时jvm可回收掉
index.cache.field.type: soft
#锁定内存
bootstrap.memory_lock: true
#索引刷新时间，默认1s
index:refresh_interval: 8s

index.number_of_shards: 2
index.number_of_replicas: 0

#压缩存储方式 默认LZ4, 开启了 DEFLATE之后，索引确实小了点，索引时间变化不大，每次索引10w进行测试的。
#index.codec: best_compression

# result size. default = 10000
index.max_result_window: 10000

threadpool:
    index:
        size: 4
        queue_size: 1000

#indices.store.throttle.type: merge 
#写磁盘类型 
#indices.store.throttle.type: none 
indices.store.throttle.max_bytes_per_sec: 500mb

#index.search.slowlog.threshold.query.warn: 10s
#index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.query.debug: 1s
#index.search.slowlog.threshold.query.trace: 500ms
#
#index.search.slowlog.threshold.fetch.warn: 1s
#index.search.slowlog.threshold.fetch.info: 800ms
#index.search.slowlog.threshold.fetch.debug: 500ms
#index.search.slowlog.threshold.fetch.trace: 200ms
#
#index.indexing.slowlog.threshold.index.warn: 10s
#index.indexing.slowlog.threshold.index.info: 5s
#index.indexing.slowlog.threshold.index.debug: 2s
#index.indexing.slowlog.threshold.index.trace: 500ms


# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
# cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
# node.name: node-1
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
# path.data: /path/to/data
#
# Path to log files:
#
# path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.memory_lock: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
# http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]

# discovery.zen.ping.unicast.hosts: ["127.0.0.1", "172.16.2.248", "172.16.4.33"]
discovery.zen.ping.unicast.hosts: ["172.16.7.238"]
discovery.zen.ping_timeout: 10s
discovery.zen.minimum_master_nodes: 1

#集群中没有master时 拒绝哪些操作 默认为写操作
discovery.zen.no_master_block: write

# How often a node gets pinged. Defaults to 1s.
discovery.zen.fd.ping_interval: 5s

#默认时间为ping_timeout的20倍
#discovery.zen.join_timeout: 120s

#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
